version: "3"

services:
  app:
    container_name: events_app
    build:
      context: ..
      dockerfile: ./cicd/Dockerfile
    ports:
      - 80:80
    depends_on:
      - database
  
  database:
    image: postgres:15
    container_name: events_db
    ports:
      - 5433:5432  # База данных будет доступна из интернета, не забывайте выставить пароль!
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust


